remote_theme: pages-themes/architect@v0.2.0
theme: jekyll-theme-architect

title: Programmer's Mind
description: It is important to never stop questioning. Curiousity has it's own reason for existing. ~Albert Einstein. 
